### ISSUE TITLE
Wireframe Desktop

### ISSUE THREAD

**Issue by LilithSWE** [LilithSWE/Pixel-Picture-Multiplayer-Game-with-Live-Chat#41]

**Comment by Ogen1998** [comment]
loginPage
![Image](https://github.com/LilithSWE/Pixel-Picture-Multiplayer-Game-with-Live-Chat/assets/146852586/50d05938-8294-48de-be04-09828592d58a)


startPage
![Image](https://github.com/LilithSWE/Pixel-Picture-Multiplayer-Game-with-Live-Chat/assets/146852586/abd1b827-fa38-4120-b24a-407a0d1efddd)

gamePage
![Image](https://github.com/LilithSWE/Pixel-Picture-Multiplayer-Game-with-Live-Chat/assets/146852586/ff3bf8bc-001e-4422-93ca-29c4a4956522)



gamePagePopup
![Image](https://github.com/LilithSWE/Pixel-Picture-Multiplayer-Game-with-Live-Chat/assets/146852586/33a093cf-9571-4fc7-ad09-d27a863483b8)
